# Use a specific Node.js version
FROM node:14-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port on which your application will run
EXPOSE 3000

# Specify the command to run on container start
CMD ["npm", "start"]
